[phases.setup]
nixPkgs = ["erlang", "elixir", "redis"]

[phases.install]
cmds = ["mix local.hex --force", "mix local.rebar --force", "mix deps.get"]

[phases.build]
cmds = ["mix compile"]

[start]
cmd = "mix run --no-halt"
