name: Docker Image CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag phineas/Exoix:latest
      - name: Docker Push
        run: docker push phineas/Exoix
